"""Per-entrance certified cutoff references and explicit training contract.

Public prefixes are generated by a world-independent uniform policy. The
public posterior is therefore the parent's prior; each root information cell
conditions it on own type and received private answers. Every entrance is
solved afresh with its own next-own horizon. No internal parent-tree label is
silently reused with a shifted endpoint.
"""
from pathlib import Path
import time

import numpy as np

from training.b_sft.preference_contract import world_weights
from training.b_sft.shared_teacher import SearchLimit
from training.b_sft.social_private_teacher import PrivateInvestigationRules
from .bounded import BoundedPrivateWindow, resolve_horizon
from .common import digest, save_reference, file_hash, replay_node

BACKEND = 'bounded-next-own-v1'
CONTRACT = dict(version=BACKEND,
    slices_reward='Own native commitment utility at the recorded absolute cutoff',
    slices_continuation='Selected certified profile for others and for focal after k decisions, only until the same cutoff',
    selfplay_reward='Own native terminal utility in the complete parent game',
    evaluation='Complete native games for team and focal_reference; slice D uses cutoff utility separately',
    focal_reference='Receding certified next-own oracle; public prior updated by reference-action likelihoods; focal interventions are exogenous',
    prompt='Cutoff and controlled-decision budget are disclosed only in slice mode',
    interpretation='Comparison of complete training procedures, including different reward horizons; not an isolated C-selection ablation')


def settings(config):
    return dict(lookahead_rr=config.get('lookahead_rr', 1),
        max_nodes=config['max_nodes'], seconds=config['solver_seconds'],
        max_joint_cells=config.get('max_joint_cells', 4096),
        max_joint_evaluations=config.get('max_joint_evaluations', 160))


def public_entrances(rules, seed, trajectories, maximum, prescribed=()):
    """Include initial root, then round-robin roles/depths from uniform paths."""
    rng = np.random.default_rng(seed)
    paths = {(): rules.initial()}
    for _ in range(trajectories):
        node, history = rules.initial(), []
        while rules.actor(node) is not None:
            ai = int(rng.integers(len(rules.actions(node))))
            node = rules._apply(node, rules.actions(node)[ai]); history.append(ai)
            if rules.actor(node) is not None:
                paths[tuple(history)] = node
    pools = {}
    for history, node in paths.items():
        if history:
            pools.setdefault((node.state.turn_index // rules.spec.n_players, rules.actor(node)), []).append((history, node))
    # Prescribed legal prefixes are exogenous public interventions, chosen
    # independently of hidden worlds, with exactly the same public prior.
    result = [(tuple(h), replay_node(rules, h)) for h in prescribed]
    if not any(not h for h, _ in result):
        result.append(((), paths[()]))
    used = {h for h, _ in result}
    while pools and len(result) < maximum:
        for key in sorted(list(pools)):
            item = pools[key].pop(0)
            if item[0] not in used:
                result.append(item); used.add(item[0])
            if not pools[key]:
                del pools[key]
            if len(result) >= maximum:
                break
    return result[:maximum]


def select_bounded_slices(raw, parent_id, seed, config, output):
    from .build import cap_slices, measure_entrance
    from .diagnose_bounded import count_bounded_nodes, root_entrances
    rules = PrivateInvestigationRules(raw)
    prior = world_weights(rules.worlds, raw['background_prior'])
    references, retained, diagnostics = {}, [], []
    roots = public_entrances(rules, seed, config['entrance_trajectories'], config['max_entrances'],
                            raw.get('slice_setup_histories', ()))
    depths = config.get('lookahead_depths') or [config.get('lookahead_rr', 1)]
    seen_endpoints = set()
    for history, node, depth in ((h, n, d) for h, n in roots for d in depths):
        endpoint = (tuple(history), resolve_horizon(rules, node, depth)['cutoff'])
        if endpoint in seen_endpoints:
            continue
        seen_endpoints.add(endpoint)
        started = time.monotonic()
        record = dict(history=list(history), actor=rules.actor(node), proposal_turn=node.state.turn_index, lookahead_rr=depth)
        try:
            opts = settings(config)
            opts['lookahead_rr'] = depth
            count = count_bounded_nodes(rules, node, opts['lookahead_rr'])
            if count['unfolded_public_history_nodes'] > opts['max_nodes']:
                raise SearchLimit('Bounded data public-tree node budget exceeded')
            tree = BoundedPrivateWindow(rules, node, rules.worlds, world_weights=prior, **opts).solve()
            audit = tree.audit_native()
            reference_id = digest((parent_id, history, opts))[:24]
            rows = []
            for entrance in root_entrances(tree):
                entrance.update(history=list(history), reference_id=reference_id,
                    absolute_cutoff=tree.cutoff, entrance_policy='world-independent-public-prefix-v1',
                    lookahead_rr=depth)
                measured, _ = measure_entrance(tree, entrance, parent_id, config)
                rows.extend(measured)
            if rows:
                name = f'references/{reference_id}.npz'
                save_reference(Path(output) / name, tree)
                references[reference_id] = dict(id=reference_id, history=list(history), settings=opts,
                    world_weights=prior.tolist(), certificate=tree.certificate, native_audit=audit,
                    reference_file=name, reference_sha256=file_hash(Path(output) / name))
                retained.extend(rows)
            record.update(status='certified', nodes=len(tree.entries), slices=len(rows),
                positive_S=sum(s['information_positive'] for s in rows))
        except SearchLimit as exc:
            record.update(status='unavailable', reason=str(exc), oracle_label=None)
        record['seconds'] = time.monotonic() - started
        diagnostics.append(record)
        if config.get('require_initial_reference') and not history and record['status'] != 'certified':
            break
    selected = cap_slices(retained, config)
    used = {s['reference_id'] for s in selected}
    return selected, len(roots), diagnostics, {k: v for k, v in references.items() if k in used}, prior.tolist()


def load_reference(dataset, parent, record):
    """Rebuild exact native tree and independently certify stored probabilities."""
    from .equilibrium import certify_policy
    rules = dataset.rules(parent)
    root = replay_node(rules, record['history'])
    opts = dict(record['settings']); opts['seconds'] = max(120, opts['seconds'])
    tree = BoundedPrivateWindow(rules, root, rules.worlds,
                               world_weights=record['world_weights'], **opts)
    path = dataset.root / record['reference_file']
    if file_hash(path) != record['reference_sha256']:
        raise ValueError('Bounded reference file changed')
    with np.load(path, allow_pickle=False) as saved:
        flat = saved['probabilities']
    cursor = 0
    for i, entry in enumerate(tree.entries):
        if entry.actor is not None:
            size = len(entry.actions) * tree.w
            tree.policy[i] = flat[cursor:cursor+size].reshape(len(entry.actions), tree.w).copy()
            cursor += size
    if cursor != len(flat):
        raise ValueError('Bounded reference shape mismatch')
    identity, _ = tree.reference_identity()
    if identity != record['certificate']['policy_sha256']:
        raise ValueError('Bounded reference contract identity mismatch')
    checked = certify_policy(tree, tree.epsilon)
    if checked is None:
        raise ValueError('Stored bounded reference failed independent certification')
    tree.values, tree.certificate = checked['values'], dict(record['certificate'])
    tree.audit_native()
    return tree


class RecedingReference:
    """Frozen oracle algorithm for full-game focal evaluation, never training.

    Focal model actions are exogenous interventions; reference actions update
    the public posterior using their actual private-information policy. Private
    answers refine each player's own partition, never the public posterior.
    Solver failures propagate as infrastructure errors, with no fallback.
    """
    def __init__(self, dataset, parent):
        from .bounded_cache import BoundedProblemCache
        self.rules = dataset.rules(parent)
        self.raw = parent['raw']
        self.weights = np.asarray(parent['world_weights'], dtype=float).copy()
        self.worlds = self.rules.worlds
        self.options = settings(dataset.manifest['config'])
        self.cache = BoundedProblemCache(max_entries=1)
        self.seconds = 0.
        self.solves = 0

    def probabilities(self, history):
        started = time.monotonic()
        root = replay_node(self.rules, history)
        active = np.flatnonzero(self.weights > 0)
        result = self.cache.solve(self.rules, root, [self.worlds[i] for i in active],
                                 world_weights=self.weights[active], raw=self.raw, **self.options)
        probabilities = np.zeros((len(self.rules.actions(root)), len(self.worlds)))
        probabilities[:, active] = result.tree.policy[0]
        self.seconds += time.monotonic() - started
        self.solves += int(not result.cache_hit)
        return probabilities

    def observe_reference(self, probabilities, action):
        self.weights *= probabilities[action]
        if self.weights.sum() <= 0:
            raise ValueError('Reference action has zero public likelihood')
        self.weights /= self.weights.sum()
