"""Freeze audited inputs and isolate the existing outcome runtime. CPU only."""
import ast
import hashlib
import json
from pathlib import Path
import re
import tarfile

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'examples/social_mixed/data'
VENDOR = ROOT / 'training/social_mixed/frozen'


def digest(data):
    return hashlib.sha256(data).hexdigest()


def main():
    archive = ROOT / 'examples/outcome_selfplay_nus/runtime_v4.tar.gz'
    expected = archive.with_suffix('.sha256').read_text().split()[0] if archive.with_suffix('.sha256').exists() else (archive.parent/'runtime_v4.sha256').read_text().split()[0]
    assert digest(archive.read_bytes()) == expected
    modules = {}
    with tarfile.open(archive) as tar:
        manifest = json.loads(tar.extractfile('outcome_rollout_runtime/runtime_manifest.json').read())
        for member in tar.getmembers():
            if not member.name.endswith('.py'):
                continue
            name = member.name.removeprefix('outcome_rollout_runtime/')
            data = tar.extractfile(member).read()
            assert digest(data) == manifest['files'][name]
            if name.startswith('runs/outcome_selfplay_screen/'):
                module = Path(name).stem
            else:
                module = name.removeprefix('third_party/negotiation_benchmark/src/').removesuffix('.py').replace('/', '.')
            modules[module] = data.decode()
        curriculum = json.loads(tar.extractfile('outcome_rollout_runtime/runs/outcome_selfplay_screen/curriculum.json').read())
    # Preserve implementations; change only import namespaces, preventing frozen
    # self-play rules from shadowing mutable B/P teacher modules in one process.
    needed = set()
    def visit(name):
        if name in needed or name not in modules:
            return
        needed.add(name)
        for node in ast.walk(ast.parse(modules[name])):
            if isinstance(node, ast.ImportFrom) and not node.level:
                visit(node.module)
                for alias in node.names:
                    visit(f'{node.module}.{alias.name}')
            elif isinstance(node, ast.Import):
                for alias in node.names:
                    visit(alias.name)
    for name in ('outcome_rules', 'selfplay_prompt', 'bp_display'):
        visit(name)
    prefix = 'training.social_mixed.frozen.'
    VENDOR.mkdir(parents=True, exist_ok=True)
    (VENDOR/'__init__.py').write_text('"""Generated by examples/social_mixed/prepare.py; frozen game implementation."""\n')
    mapping = {}
    for name in sorted(needed):
        text = modules[name]
        # All dependencies in this closure use absolute from-imports or aliased imports.
        for dep in sorted(needed, key=len, reverse=True):
            text = re.sub(r'(?m)^(\s*from )'+re.escape(dep)+r'( import )', r'\g<1>'+prefix+dep+r'\2', text)
            text = re.sub(r'(?m)^(\s*import )'+re.escape(dep)+r'( as )', r'\g<1>'+prefix+dep+r'\2', text)
        text = re.sub(r'(?m)^(\s*from )training\.b_sft( import )', r'\g<1>'+prefix+r'training.b_sft\2', text)
        text = re.sub(r'(?m)^sys\.path\.insert\(.*\)\n', '', text)
        if 'sys.path' in text:
            raise RuntimeError(f'Unexpected path mutation in dependency {name}')
        path = VENDOR / (name.replace('.', '/')+'.py')
        path.parent.mkdir(parents=True, exist_ok=True)
        for parent in path.parents:
            if parent == VENDOR.parent:
                break
            (parent/'__init__.py').touch(exist_ok=True)
        path.write_text(text)
        mapping[name] = dict(source_sha256=digest(modules[name].encode()), frozen_sha256=digest(text.encode()))
    OUT.mkdir(parents=True, exist_ok=True)
    source = ROOT/'examples/social_bp/data_two_a100_v1/tasks.jsonl'
    audit = json.loads((source.parent/'solver_audit.json').read_text())
    assert audit['tasks_sha256'] == digest(source.read_bytes())
    tasks = [json.loads(line) for line in source.read_text().splitlines() if line.strip()]
    files = {}
    def write(name, rows):
        payload = ''.join(json.dumps(row, ensure_ascii=False)+'\n' for row in rows).encode()
        (OUT/name).write_bytes(payload)
        files[name] = dict(sha256=digest(payload), count=len(rows))
    for split in ('train', 'validation'):
        write(f'bp_{split}.jsonl', [t for t in tasks if t['split']==split and not (t['task']=='B' and t.get('direct_answer'))])
    instances = {r['id']:r for r in curriculum['instances']}
    resets = [dict(r, split='train', raw=instances[r['instance_id']]['raw']) for r in curriculum['resets']]
    write('selfplay_train.jsonl', resets)
    evaluation = json.loads((ROOT/'runs/outcome_selfplay_screen/eval_splits.json').read_text())
    write('selfplay_validation.jsonl', [r for r in evaluation['records'] if r['split']=='validation'])
    result = dict(version='social-mixed-v1', outcome_archive_sha256=expected, bp_source_sha256=digest(source.read_bytes()),
                  files=files, frozen_modules=mapping, test_included=False,
                  selfplay_selection='Existing full-game reset bank; no solver or model-success filtering',
                  limitations='60 training resets from six named templates (some share a source geometry); not 60 independent strategic families.')
    (OUT/'manifest.json').write_text(json.dumps(result, indent=2)+'\n')
    print(json.dumps(files, indent=2))


if __name__ == '__main__':
    main()
